AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Resources:
  TuBoleteraApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  TestPageVisitFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: handler.testPageVisit
      Runtime: nodejs12.x
      CodeUri: ./hello
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TuBoleteraTable
      Events:
        TuBoleteraAPI:
          Type: Api
          Properties:
            RestApiId: !Ref TuBoleteraApi
            Path: /pageVisit/test
            Method: POST

  PageVisitFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: handler.pageVisit
      Runtime: nodejs12.x
      CodeUri: ./hello
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TuBoleteraTable
      Events:
        TuBoleteraAPI:
          Type: Api
          Properties:
            RestApiId: !Ref TuBoleteraApi
            Path: /pageVisit
            Method: POST

  TestKnowMoreFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: handler.testKnowMore
      Runtime: nodejs12.x
      CodeUri: ./hello
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TuBoleteraTable
      Events:
        TuBoleteraAPI:
          Type: Api
          Properties:
            RestApiId: !Ref TuBoleteraApi
            Path: /knowMore/test
            Method: POST

  KnowMoreFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: handler.knowMore
      Runtime: nodejs12.x
      CodeUri: ./hello
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TuBoleteraTable
      Events:
        TuBoleteraAPI:
          Type: Api
          Properties:
            RestApiId: !Ref TuBoleteraApi
            Path: /knowMore
            Method: POST

  GetTestDataFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: handler.getTestData
      Runtime: nodejs12.x
      CodeUri: ./hello
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TuBoleteraTable
      Events:
        TuBoleteraAPI:
          Type: Api
          Properties:
            RestApiId: !Ref TuBoleteraApi
            Path: /data/test
            Method: GET

  GetDataFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: handler.getData
      Runtime: nodejs12.x
      CodeUri: ./hello
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TuBoleteraTable
      Events:
        TuBoleteraAPI:
          Type: Api
          Properties:
            RestApiId: !Ref TuBoleteraApi
            Path: /data
            Method: GET

  TuBoleteraTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "name"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "name"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "TuBoleteraTable"

Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region

  ApiId:
    Description: "API ID"
    Value: !Ref TuBoleteraApi

  ApiUrl:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${TuBoleteraApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"
